[package]
name = "dmm"
version = "0.1.0"
edition = "2021"
authors = [ "Rowan S-L <r@fawkes.io>" ]
description = "DMM - The Declarative Music Manager"
repository = "https://git.fawkes.io/mtnash/dmm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive", "wrap_help", "cargo", "unicode", "string", "unstable-styles"] }
heck = "0.4.1"
ron = "0.8.1"
serde = { version = "1.0.193", features = ["derive"] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
notify-rust = "4.10.0"
symphonia = { version = "0.5.3", features = ["mp3", "aac", "alac"] }
cpal = "0.15.2"
arrayvec = "0.7.4"
rb = "0.4.1"
rubato = "0.14.1"
tokio = { version = "1.34.0", features = ["full"] }
futures = "0.3.29"
async-trait = "0.1.74"
ratatui = { version = "0.24.0", features = ["serde", "macros"] }
flume = "0.11.0"
fuzzy-matcher = "0.3.7"
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "local-time"] }
lazy_static = "1.4.0"
directories = "5.0.1"
color-eyre = "0.6.2"
log = "0.4.20"
better-panic = "0.3.0"
libc = "0.2.148"
strip-ansi-escapes = "0.2.0"
human-panic = "1.2.0"
tokio-util = "0.7.9"
crossterm = { version = "0.27.0", features = ["serde", "event-stream"] }
signal-hook = "0.3.17"
config = "0.13.4"
derive_deref = "1.1.1"
serde_json = "1.0.108"
json5 = "0.4.1"

[profile.release]
lto = true
strip = true
codegen-units = 1
