[package]
name = "dmm"
version = "0.1.0"
edition = "2021"
authors = [ "Rowan S-L <r@fawkes.io>" ]
description = "DMM - The Declarative Music Manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
clap = { version = "4.4.8", features = ["derive", "wrap_help", "cargo"] }
heck = "0.4.1"
ron = "0.8.1"
serde = { version = "1.0.193", features = ["derive"] }
