[package]
name = "dmm"
version = "0.1.0"
edition = "2021"
authors = [ "Rowan S-L <r@fawkes.io>" ]
description = "DMM - The Declarative Music Manager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
clap = { version = "4.4.8", features = ["derive", "wrap_help", "cargo"] }
heck = "0.4.1"
ron = "0.8.1"
serde = { version = "1.0.193", features = ["derive"] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
notify-rust = "4.10.0"
symphonia = { version = "0.5.3", features = ["mp3", "aac", "alac"] }
log = "0.4.20"
pretty_env_logger = "0.5.0"
cpal = "0.15.2"
arrayvec = "0.7.4"
rb = "0.4.1"
rubato = "0.14.1"
tokio = { version = "1.34.0", features = ["full"] }
